username = input('Введите имя пользователя: ')
title = input('Заголовок заметки: ')
content = input('Описание заметки: ')
status = input('Статус: ')
created_date = input('Дата создания заметки: ')
issue_date = input('Дата дедлайна: ')

print(f'Имя пользователя: {username}')
print(f'Заголовок: {title}')
print(f'Описание заметки: {content}')
print(f'Ваш статус: {status}')
print(f'Дата создания заметки: {created_date}')
print(f'Дата дедлайна: {issue_date}')
